### ISSUE TITLE
CUDA Driver not Recognized

### ISSUE THREAD

**Issue by Heatshiver** [lltcggie/waifu2x-caffe#163]
I have the latest NVIDIA drivers, CUDA toolkit, and cuDNN installed. I placed "cudnn64_7.dll" in the waifu2x-caffe folder.

Despite all this, I always get the error that the CUDA driver could not be detected...

I am using a GTX 1080Ti.

**Comment by Serovea** [comment]
2nd

I'm having this problem aswell.

**Comment by gmikhail** [comment]
I just download [cudnn-10.1-windows10-x64-v7.5.1.10.zip](https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v7.5.1/prod/10.1_20190418/cudnn-10.1-windows10-x64-v7.5.1.10.zip) (registration required) and copied cudnn64_7.dll (374 MB) to the waifu2x-caffe folder and it worked. "Test cuDNN" passes successfully.

CUDA toolkit not required.

**Comment by psomell** [comment]
不行哦

**Comment by viktor02** [comment]
> 
> 
> I just download [cudnn-10.1-windows10-x64-v7.5.1.10.zip](https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v7.5.1/prod/10.1_20190418/cudnn-10.1-windows10-x64-v7.5.1.10.zip) (registration required) and copied cudnn64_7.dll (374 MB) to the waifu2x-caffe folder and it worked. "Test cuDNN" passes successfully.
> 
> CUDA toolkit not required.

I put cudnn64_7.dll for win7 in the caffe folder, installed the cuda toolkit and nothing, I still get the error.
Win7, GTS 450.

**Comment by marktaiwan** [comment]
> I just download [cudnn-10.1-windows10-x64-v7.5.1.10.zip](https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v7.5.1/prod/10.1_20190418/cudnn-10.1-windows10-x64-v7.5.1.10.zip) (registration required) and copied cudnn64_7.dll (374 MB) to the waifu2x-caffe folder and it worked. "Test cuDNN" passes successfully.
> 
> CUDA toolkit not required.

Thanks, that works for me on version 1.2.0.2
